version: "3.0"

services:

  opensearch:
    container_name: opensearch-node1
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION_TAG}
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    networks:
      - opensearch-net

  opensearch-dashboard:
    container_name: opensearch-dashboard
    image: opensearchproject/opensearch-dashboards:${OPENSEARCH_VERSION_TAG}
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    ports:
      - 5601:5601
    networks:
      - opensearch-net
    depends_on:
      - opensearch

networks:
  opensearch-net:
    driver: bridge