index:
  refresh_interval: -1
analysis:
  tokenizer:
    onetwogram_tokenizer:
      type: ngram
      min_gram: 1
      max_gram: 2
  analyzer:
    onetwogram_analyzer:
      tokenizer: onetwogram_tokenizer